# Generated by Django 5.2.13 on 2026-04-18 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="document_type",
            field=models.CharField(default="other", max_length=100),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="contact_email",
            field=models.EmailField(
                default="contact@mitchelltechgroup.com", max_length=254
            ),
        ),
    ]
