# Generated by Django 5.2.13 on 2026-04-18 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="billing_type",
            field=models.CharField(default="hourly", max_length=100),
        ),
    ]
