# Generated by Django 5.2.13 on 2026-06-01 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("public", "0002_alter_service_billing_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicerequest",
            name="services_requested",
            field=models.ManyToManyField(
                blank=True, related_name="consultation_requests", to="public.service"
            ),
        ),
    ]
