# Generated by Django 5.2.13 on 2026-06-16 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0003_add_services_requested_to_servicerequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequestDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='service_requests/')),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('service_request', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='documents', to='public.servicerequest')),
            ],
            options={
                'verbose_name': 'Service Request Document',
                'verbose_name_plural': 'Service Request Documents',
                'ordering': ['-created_at'],
            },
        ),
    ]
