# Generated by Django 5.2.13 on 2026-04-18 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consultingproject",
            name="project_type",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="category",
            field=models.CharField(default="general", max_length=100),
        ),
    ]
