# Generated by Django 5.2.13 on 2026-04-19 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0002_alter_consultingproject_project_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectmilestone",
            name="milestone_type",
            field=models.CharField(
                choices=[
                    ("sprint", "Sprint"),
                    ("milestone", "Milestone"),
                    ("release", "Release"),
                ],
                default="milestone",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="projectmilestone",
            name="sprint_goal",
            field=models.TextField(
                blank=True, help_text="Sprint goal or acceptance criteria"
            ),
        ),
        migrations.AddField(
            model_name="projectmilestone",
            name="sprint_number",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Sprint number (for sprint-type milestones)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="projectmilestone",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="projectmilestone",
            name="story_points_completed",
            field=models.PositiveIntegerField(
                default=0, help_text="Story points completed"
            ),
        ),
        migrations.AddField(
            model_name="projectmilestone",
            name="story_points_planned",
            field=models.PositiveIntegerField(
                default=0, help_text="Total story points planned"
            ),
        ),
    ]
