# Generated by Django 5.2.13 on 2026-04-18 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="activity_type",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="lead",
            name="source",
            field=models.CharField(default="website", max_length=100),
        ),
    ]
