# Generated by Django 5.2.13 on 2026-04-18 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoicing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="method",
            field=models.CharField(max_length=100),
        ),
    ]
