# Generated by Django 5.2.12 on 2026-03-30 01:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("crm", "0001_initial"),
        ("tickets", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AvailabilitySlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "day_of_week",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ]
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availability_slots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Availability Slot",
                "verbose_name_plural": "Availability Slots",
                "ordering": ["day_of_week", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="Meeting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "meeting_uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "meeting_type",
                    models.CharField(
                        choices=[
                            ("VIDEO", "Video Call"),
                            ("PHONE", "Phone Call"),
                            ("IN_PERSON", "In Person"),
                            ("DEMO", "Product Demo"),
                            ("CONSULTING", "Consulting Session"),
                            ("SUPPORT", "Support Call"),
                            ("PROJECT_REVIEW", "Project Review"),
                        ],
                        default="VIDEO",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Scheduled"),
                            ("CONFIRMED", "Confirmed"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                            ("NO_SHOW", "No Show"),
                            ("RESCHEDULED", "Rescheduled"),
                        ],
                        default="SCHEDULED",
                        max_length=20,
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                (
                    "timezone",
                    models.CharField(default="America/Chicago", max_length=50),
                ),
                (
                    "video_provider",
                    models.CharField(
                        choices=[
                            ("ZOOM", "Zoom"),
                            ("GOOGLE_MEET", "Google Meet"),
                            ("TEAMS", "Microsoft Teams"),
                            ("OTHER", "Other"),
                            ("NONE", "None (Phone/In-Person)"),
                        ],
                        default="ZOOM",
                        max_length=20,
                    ),
                ),
                (
                    "meeting_url",
                    models.URLField(blank=True, help_text="Join URL for participants"),
                ),
                ("host_url", models.URLField(blank=True, help_text="Host start URL")),
                ("meeting_id", models.CharField(blank=True, max_length=100)),
                ("meeting_password", models.CharField(blank=True, max_length=50)),
                (
                    "external_meeting_id",
                    models.CharField(
                        blank=True, help_text="ID from video provider", max_length=200
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=300)),
                ("agenda", models.TextField(blank=True)),
                (
                    "notes",
                    models.TextField(blank=True, help_text="Meeting notes/minutes"),
                ),
                (
                    "action_items",
                    models.TextField(blank=True, help_text="Follow-up action items"),
                ),
                ("reminder_sent", models.BooleanField(default=False)),
                ("reminder_24h_sent", models.BooleanField(default=False)),
                ("reminder_1h_sent", models.BooleanField(default=False)),
                ("is_recorded", models.BooleanField(default=False)),
                ("recording_url", models.URLField(blank=True)),
                ("recording_password", models.CharField(blank=True, max_length=50)),
                (
                    "client_join_token",
                    models.UUIDField(default=uuid.uuid4, editable=False),
                ),
                ("allow_client_join", models.BooleanField(default=True)),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="meetings",
                        to="crm.contact",
                    ),
                ),
                (
                    "host",
                    models.ForeignKey(
                        blank=True,
                        help_text="Meeting host (may differ from organizer)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hosted_meetings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="meetings",
                        to="crm.organization",
                    ),
                ),
                (
                    "organizer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organized_meetings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "participants",
                    models.ManyToManyField(
                        blank=True,
                        related_name="meeting_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="meetings",
                        to="tickets.consultingproject",
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="meetings",
                        to="tickets.ticket",
                    ),
                ),
            ],
            options={
                "verbose_name": "Meeting",
                "verbose_name_plural": "Meetings",
                "ordering": ["-start_time"],
            },
        ),
        migrations.CreateModel(
            name="MeetingAttendee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("name", models.CharField(blank=True, max_length=200)),
                (
                    "rsvp_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ACCEPTED", "Accepted"),
                            ("DECLINED", "Declined"),
                            ("TENTATIVE", "Tentative"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "attendance_status",
                    models.CharField(
                        choices=[
                            ("NOT_YET", "Not Yet"),
                            ("ATTENDED", "Attended"),
                            ("NO_SHOW", "No Show"),
                            ("PARTIAL", "Partial"),
                        ],
                        default="NOT_YET",
                        max_length=20,
                    ),
                ),
                ("joined_at", models.DateTimeField(blank=True, null=True)),
                ("left_at", models.DateTimeField(blank=True, null=True)),
                ("invitation_sent", models.BooleanField(default=False)),
                ("invitation_sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meeting_attendances",
                        to="crm.contact",
                    ),
                ),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendees",
                        to="meetings.meeting",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meeting_attendances",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Meeting Attendee",
                "verbose_name_plural": "Meeting Attendees",
            },
        ),
        migrations.CreateModel(
            name="MeetingRecording",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                ("recording_url", models.URLField()),
                ("password", models.CharField(blank=True, max_length=50)),
                ("duration_seconds", models.PositiveIntegerField(default=0)),
                ("file_size_bytes", models.PositiveBigIntegerField(default=0)),
                ("transcript", models.TextField(blank=True)),
                ("transcript_url", models.URLField(blank=True)),
                ("external_id", models.CharField(blank=True, max_length=200)),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recordings",
                        to="meetings.meeting",
                    ),
                ),
            ],
            options={
                "verbose_name": "Meeting Recording",
                "verbose_name_plural": "Meeting Recordings",
            },
        ),
        migrations.AddIndex(
            model_name="meeting",
            index=models.Index(
                fields=["start_time", "status"], name="meetings_me_start_t_7e0ef1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="meeting",
            index=models.Index(
                fields=["organizer", "status"], name="meetings_me_organiz_965dcc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="meeting",
            index=models.Index(
                fields=["meeting_uuid"], name="meetings_me_meeting_e4fec3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="meeting",
            index=models.Index(
                fields=["client_join_token"], name="meetings_me_client__c3b9be_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="meetingattendee",
            unique_together={
                ("meeting", "contact"),
                ("meeting", "email"),
                ("meeting", "user"),
            },
        ),
    ]
