# Generated by Django 5.2.13 on 2026-04-18 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meeting",
            name="meeting_type",
            field=models.CharField(default="VIDEO", max_length=100),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="video_provider",
            field=models.CharField(default="ZOOM", max_length=100),
        ),
    ]
